/*mysql -P 3600 -uroot -p*/
CREATE DATABASE GRACURRI_USER;
CREATE TABLE USERS(id INT(11) NOT NULL, EMAIL 
VARCHAR(40) NOT NULL, PW VARCHAR(11) NOT NULL, username VARCHAR(5) NOT NULL, major VARCHAR(30) NOT NULL,
PRIMARY KEY(id));